[project]
name = "curso-langchain-langraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain==0.3.*",
    "langchain-openai",
    "langchain-google-genai",
    "streamlit",
    "dotenv",
]
